name: Broadcasting Review afert Pull Request

on:
  pull_request:
    types: [ opened, ready_for_review ]


jobs:
  broadcasting_review:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
