name: Broadcasting Review afert Pull Request

on:
  pull_request:
    types: [ opened, ready_for_review ]


jobs:
  broadcasting_review:
    runs-on: ubuntu-latest
    
    steps:
    - name: slack-send
      uses: slackapi/slack-github-action@v1.15.0
      with:
        channel-id: 'android-develop'
        slack-message: 'posting from a github action!'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_WEBHOOK }}

    - name: Get PR Info Action
      id: pr_info
      uses: OneKeyHQ/onekey-github-actions/get-pr-info@main
        
    - uses: 8398a7/action-slack@v3
      with:
        icon_url: 'https://github.githubassets.com/images/modules/logos_page/Octocat.png'
        status: custom
        fields: author
        custom_payload: |
          {
            text: "Code Review",
            attachments: [{
              "author_name": "${process.env.AS_AUTHOR}",
              fallback: 'fallback',
              color: '00B812',
              title: 'Code Review',
              text: '${process.env.AS_AUTHOR} 提交了 ${{ steps.pr_info.outputs.title }}\n${{ steps.pr_info.outputs.content_body }}\n 快来 Review Code ${{ steps.pr_info.outputs.url }}'
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.ANDROID_SLACK_WEBHOOK }}
      if: always() # Pick up events even if the job fails or is canceled.
