name: Notice Slack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Notify Slack
      # You may pin to the exact commit or the version.
      # uses: slackapi/slack-github-action@d5d276d7ae0f38f29322b80da9baf985cc80f8b1
        uses: drilonrecica/action-slack-notify@0.0.6
        env:
          SLACK_MESSAGE: "{\"attachments\":[{\"blocks\":[{\"type\":\"header\",\"text\":{\"type\":\"plain_text\",\"text\":\"App 有新的更新\"}},{\"type\":\"section\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*VersionName*\\n2.1.3\"},{\"type\":\"mrkdwn\",\"text\":\"*VersionCode*\\n4001865\"}]},{\"type\":\"section\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*Platform*\\nandroid\"},{\"type\":\"mrkdwn\",\"text\":\"*Download*\\nhttp://www.baidu.com\"}]},{\"type\":\"section\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*Release Notes*\\nandroid\"}]},{\"type\":\"actions\",\"elements\":[{\"type\":\"button\",\"text\":{\"type\":\"plain_text\",\"text\":\"前往下载\"},\"value\":\"http://www.baidu.com\",\"action_id\":\"actionId-0\"}]}]}]}"
          SLACK_TITLE: Post Title
          SLACK_USERNAME: 测试一下
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
