name: Upload Firim Test 4

on:
  workflow_dispatch:
    inputs:
      changelog:
        description: 'test'
        required: false
        default: 'Upload Test'

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        
    - name: test
      run: |
        pwd
        export COMMIT_COUNT=`git rev-list HEAD --count`
        echo "COMMIT_COUNT=$COMMIT_COUNT" >> $GITHUB_ENV
        echo "test=123456" >> $GITHUB_ENV
        
    - name: test
      run: |
        echo env COMMIT_COUNT "${{ env.COMMIT_COUNT }}"
        echo env test "${{ env.test }}"
        
    - name: Get artifacts info
      uses: OneKeyHQ/onekey-github-actions/get-artifacts-info@main
      id: artifacts_info
      with:
        api-token: ${{ secrets.FIRIM_TOKEN }}
        artifact-file-path: ./app-foretime-debug.apk
        version-suffix: Alpha
        
    - name: Print result
      run: | 
        echo artifact-type ${{ steps.artifacts_info.outputs.artifact-type }}
        echo artifact-bundle-id ${{ steps.artifacts_info.outputs.artifact-bundle-id }}
        echo artifact-version-code ${{ steps.artifacts_info.outputs.artifact-version-code }}
        echo artifact-version-name ${{ steps.artifacts_info.outputs.artifact-version-name }}
        echo artifact-name ${{ steps.artifacts_info.outputs.artifact-name }}
