name: Upload Firim Test3

on:
  workflow_dispatch:
    inputs:
      changelog:
        description: 'test'
        required: false
        default: 'Upload Test'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    
    - uses: actions/cache@v2
      id: cache
      with:
        path: ~/local/rubies
        key: ruby-2.6.5
    - name: Setup Ruby, JRuby and TruffleRuby
      uses: ruby/setup-ruby@v1.77.0
      with:
        ruby-version: 2.6.5
        bundler-cache: true
    - name: install fir.im
      run: gem install fir-cli
      
    - name: Get artifacts info
      uses: OneKeyHQ/onekey-github-actions/get-artifacts-info@main
      id: artifacts_info
      with:
        api-token: ${{ secrets.FIRIM_TOKEN }}
        artifact-file-path: ./app-foretime-debug.apk
        version-suffix: Alpha
        
    - name: Use upload firim
      id: upload_info
      run: |
        fir login ${{ secrets.FIRIM_TOKEN }} 
        fir p ./app-foretime-debug.apk -R -c "${{ github.event.inputs.changelog }}" --specify-app-display-name=${{ steps.artifacts_info.outputs.artifact-version-name }}
        egrep '(Published succeed: )\S+' grep_text.txt | egrep -o '(https?):\/\/[-A-Za-z0-9+&@#/%?=~_|!:,.;]+[-A-Za-z0-9+&@#/%=~_|]'
        
    - name: Notice Slack App Update
      uses: OneKeyHQ/onekey-github-actions/notice-slack-app-update@main
      with:
        web-hook-url: ${{ secrets.SLACK_WEBHOOK }}
        artifact-download-url: ${{ steps.upload_info.outputs.artifact-download-url }}
        artifact-type:  ${{ steps.artifact_info.outputs.artifact-type }}
        artifact-bundle-id:  ${{ steps.artifact_info.outputs.artifact-bundle-id }}
        artifact-version-code:  ${{ steps.artifact_info.outputs.artifact-version-code }}
        artifact-version-name:  ${{ steps.artifact_info.outputs.artifact-version-name }}
        artifact-name:  ${{ steps.artifact_info.outputs.artifact-name }}
        change-log: ${{ github.event.inputs.changelog }}
        
    - name: Print result
      run: | 
        echo artifact-download-url ${{ steps.upload_info.outputs.artifact-download-url }}
        echo artifact-type ${{ steps.artifact_info.outputs.artifact-type }}
        echo artifact-bundle-id ${{ steps.artifact_info.outputs.artifact-bundle-id }}
        echo artifact-version-code ${{ steps.artifact_info.outputs.artifact-version-code }}
        echo artifact-version-name ${{ steps.artifact_info.outputs.artifact-version-name }}
        echo artifact-name ${{ steps.artifact_info.outputs.artifact-name }}
