name: Upload Firim Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Download a file
      uses: carlosperate/download-file-action@v1.0.3
      id: download-poetry
      with:
        file-url: 'https://a985ebfa6e.cainiaoqr.com/6f766c536d25c113422bda11f437f2a6894f3b37.apk?auth_key=1625927399-0-0-bef258d0d39609401ab7e2747e89283d'
        file-name: '1.apk'
    - name: Use upload firim
      uses: OneKeyHQ/onekey-github-actions/upload-artifact-firim@5fa5e05b767aecbbf565bb45e16e77501e4eafd5
      id: firim
      with:
        api-token: ${{ secrets.FIRIM_TOKEN }}
        upload-file-path: ${{ steps.download-poetry.outputs.file-path }}
    - name: Print result
      run: | 
        echo artifact-download-url ${{ steps.firim.outputs.artifact-download-url }}
        echo artifact-type ${{ steps.firim.outputs.artifact-type }}
        echo artifact-bundle-id ${{ steps.firim.outputs.artifact-bundle-id }}
        echo artifact-version-code ${{ steps.firim.outputs.artifact-version-code }}
        echo artifact-version-name ${{ steps.firim.outputs.artifact-version-name }}
        echo artifact-name ${{ steps.firim.outputs.artifact-name }}
