name: Upload Firim Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Download a file
      uses: carlosperate/download-file-action@v1.0.3
      id: download-poetry
      with:
        file-url: 'https://ugc-download.firqr.com/89615ac01939aff8b724cb7e3c482aefcab10534.apk?auth_key=1625925203-0-0-cfbbee11785125201877ee152eb86929'
        file-name: '1.apk'
    - name: Use upload firim
      uses: OneKeyHQ/onekey-github-actions/upload-artifact-firim@d4356424f081538756160b83781e46c1e3a20019
      id: firim
      with:
        api-token: ${{ secrets.FIRIM_TOKEN }}
        upload-file-path: ${{ steps.download-poetry.outputs.file-path }}
    - name: Print result
      run: | 
        echo artifact-download-url ${{ steps.firim.outputs.artifact-download-url }}
        echo artifact-type ${{ steps.firim.outputs.artifact-type }}
        echo artifact-bundle-id ${{ steps.firim.outputs.artifact-bundle-id }}
        echo artifact-version-code ${{ steps.firim.outputs.artifact-version-code }}
        echo artifact-version-name ${{ steps.firim.outputs.artifact-version-name }}
        echo artifact-name ${{ steps.firim.outputs.artifact-name }}
