name: Upload Firim Test

on:
  workflow_dispatch:
    inputs:
      download-url:
        description: '下载链接'
        required: true
      test:
        description: 'test'
        required: false
        default: 'The Octoverse'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: set Test System env
      run: |
        export CHANGE_LOG=`test`
    - name: Download a file
      uses: carlosperate/download-file-action@v1.0.3
      id: download-poetry
      with:
        file-url: ${{ github.event.inputs.download-url }}
        file-name: '1.apk'
    - name: Use upload firim
      uses: OneKeyHQ/onekey-github-actions/upload-artifact-firim@main
      id: firim
      with:
        api-token: ${{ secrets.FIRIM_TOKEN }}
        upload-file-path: ${{ steps.download-poetry.outputs.file-path }}
    - name: Print result
      run: | 
        echo artifact-download-url ${{ steps.firim.outputs.artifact-download-url }}
        echo artifact-type ${{ steps.firim.outputs.artifact-type }}
        echo artifact-bundle-id ${{ steps.firim.outputs.artifact-bundle-id }}
        echo artifact-version-code ${{ steps.firim.outputs.artifact-version-code }}
        echo artifact-version-name ${{ steps.firim.outputs.artifact-version-name }}
        echo artifact-name ${{ steps.firim.outputs.artifact-name }}
    - name: Notice Slack App Update
      uses: OneKeyHQ/onekey-github-actions/notice-slack-app-update@main
      with:
        web-hook-url: ${{ secrets.SLACK_WEBHOOK }}
        artifact-download-url: ${{ steps.firim.outputs.artifact-download-url }}
        artifact-type:  ${{ steps.firim.outputs.artifact-type }}
        artifact-bundle-id:  ${{ steps.firim.outputs.artifact-bundle-id }}
        artifact-version-code:  ${{ steps.firim.outputs.artifact-version-code }}
        artifact-version-name:  ${{ steps.firim.outputs.artifact-version-name }}
        artifact-name:  ${{ steps.firim.outputs.artifact-name }}
        change-log: ${{ env.CHANGE_LOG }}
